apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.yaml
  - metrics-server.yaml
  - nginx-gateway-fabric.yaml
  - prometheus-community.yaml
  - vector.yaml
  - victoriametrics.yaml
