apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - coredns
  - gateway-api
  - ingress-nginx
  - kgateway-crds
  - kgateway
  - kube-prometheus-stack
  - metrics-server
  - sources
  - vector
  - victorialogs
