apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - coredns
  - gateway-api
  - ingress-nginx
  - kube-prometheus-stack
  - nginx-gateway-fabric
  - metrics-server
  - sources
  - vector
  - victorialogs
